services:
  - type: web
    name: textify-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://textify-ai-seven.vercel.app/
